[ffi]
{{ is_shared ? '' : ';' }}extension=ffi{{ shared_library_suffix }}
; FFI API restriction. Possible values:
; "preload" - enabled in CLI scripts and preloaded files (default)
; "false"   - always disabled
; "true"    - always enabled
;ffi.enable=preload

; List of headers files to preload, wildcard patterns allowed.
; /usr/share/php{{ binary_suffix }}/preload used by for RPM packages
; /usr/local/share/php{{ binary_suffix }}/preload may be used for local files
ffi.preload=/usr/share/php{{ binary_suffix }}/preload/*.h:/usr/local/share/php{{ binary_suffix }}/preload/*.h
