[pdo_mysql]
{{ is_shared ? '' : ';' }}extension=pdo_mysql{{ shared_library_suffix }}
; Default socket name for local MySQL connects.  If empty, uses the built-in
; MySQL defaults.
pdo_mysql.default_socket={{ type == 'rpm' ? '/var/lib/mysql/mysql.sock' : '/var/run/mysqld/mysqld.sock' }}
